User's CRUD (soft deleting included)
vik0x/php_core pull request #4
Opened 2019-09-12 17:10 UTC by ManuelOviedo

- Note: migration refresh needed for already implemented instances
Resolves: User's CRUD

2019-09-12 18:06 UTC, vik0x requested changes

2019-09-12 18:06 UTC, vik0x commented on app/Http/Controllers/v1/UserController.php
> +    public function list()
```suggestion
    public function index()
```

2019-09-12 18:06 UTC, vik0x commented on app/Http/Controllers/v1/UserController.php
> +    public function create(UserCreateRequest $request, User $user)
```suggestion
    // if you want to update an user too, you could leave the $user var here, but you have a function to update the user below
    public function create(UserCreateRequest $request)
```

2019-09-12 18:06 UTC, vik0x commented on app/Http/Controllers/v1/UserController.php
> +        $user->fill($request->input())->save();
I preffer assign each attribute in the model to better understand of code

2019-09-12 18:06 UTC, vik0x commented on app/Http/Controllers/v1/UserController.php
> +                    "attributes"=> [
should we response with an array in the case where we need just one value?

2019-09-12 18:06 UTC, vik0x commented on app/Http/Controllers/v1/UserController.php
> +    public function restore($user)
Doesn't the dependencies injection work here?

2019-09-12 18:06 UTC, vik0x commented on app/Http/Requests/v1/UserCreateRequest.php
> +            'type'          => ['alpha'],
those fields are enum on the DB (type and status), so, we need to be more specific.
You could use a configuration value in config path of the project

2019-09-12 18:06 UTC, vik0x commented on app/Http/Requests/v1/UserEditRequest.php
> +            'type'          => ['alpha'],
those fields are enum on the DB (type and status), so, we need to be more specific.
You could use a configuration value in config path of the project

2019-09-12 19:19 UTC, ManuelOviedo commented on app/Http/Controllers/v1/UserController.php
> +    public function restore($user)
No. Eloquent ORM discriminates softDeleted records

2019-09-14 01:23 UTC, vik0x approved these changes

2019-09-14 01:23 UTC, merged